---
on:
  push:
    branches:
      - master

name: Purge cache
jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    steps:

    - name: Purge cache
      uses: aorfanos/cloudflare-purge-action@master
      with:
        cf_email_addr: ${{ secrets.CF_EMAIL_ADDR }}
        cf_api_key: ${{ secrets.CF_API_KEY }}
        cf_zone_id: ${{ secrets.CF_ZONE_ID }}
        cf_purge_urls: "[\"https://aorfanos.com/styles.css\",\"https://aorfanos.com/style.css\"]"
