---
on:
  push:
    branches:
      - master

name: Purge cache
jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    steps:

      - name: Purge CF cache
        uses: remotecompany/purge-cf-cache-action@v0.0.2
        with:
          cf_token: ${{ secrets.CF_TOKEN }}
          cf_zone_name: ${{ secrets.CF_ZONE_NAME }}
          cf_purge_urls: "https://aorfanos.com,https://blog.aorfanos.com"

