---
on:
  push:
    branches:
      - master

name: Purge cache
jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    steps:

    - name: Purge cache
      uses: remotecompany/purge-cf-cache-action@v0.0.1
      env:
        CF_TOKEN: ${{ secrets.CF_TOKEN }}
        CF_ZONE_NAME: ${{ secrets.CF_ZONE_NAME }}

