---
on:
  push:
    branches:
      - master

name: Purge cache
jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    steps:

    - name: Purge cache
      uses: jakejarvis/cloudflare-purge-action@master
      env:
        CLOUDFLARE_EMAIL: ${{ secrets.CF_EMAIL_ADDR }}
        CLOUDFLARE_KEY: ${{ secrets.CF_API_KEY }}
        CLOUDFLARE_ZONE: ${{ secrets.CF_ZONE_ID }}
