---
on:
  push:
    branches:
      - master

name: Purge cache
jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    steps:

    - name: Purge cache
      uses: aorfanos/cloudflare-purge-action@main
      env:
        INPUT_CF_EMAIL_ADDR: ${{ secrets.CF_EMAIL_ADDR }}
        INPUT_CF_API_KEY: ${{ secrets.CF_API_KEY }}
        INPUT_CF_ZONE_NAME: ${{ secrets.CF_ZONE_NAME }}
        INPUT_CF_PURGE_URLS: '["https://aorfanos.com/styles.css","https://aorfanos.com/style.css"]'
