---
on:
  push:
    branches:
      - master

name: Purge cache
jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    steps:
          
#    - name: Purge cache
#      uses: aorfanos/cloudflare-purge-cache-action@master
#      with:
#        authToken: ${{ secrets.CLOUDFLARE_API_KEY }}
#        siteName: ${{ secrets.CF_ZONE_NAME }}
#        authEmail: ${{ secrets.CF_EMAIL_ADDR}}
#        fileList: "[\"https://aorfanos.com/index.html\",\"http://somesite.com/cat-picture.jpg\"]"

      - uses: remotecompany/purge-cf-cache-action@main
        env:
          INPUT_CF_API_KEY: ${{ secrets.CF_API_KEY }}
          INPUT_CF_EMAIL_ADDR: ${{ secrets.CF_EMAIL_ADDR }}
          INPUT_CF_ZONE_NAME: ${{ secrets.CF_ZONE_NAME }}
#          cf_random_thing: "foo"
